#!/bin/bash
# This script was mostly generated by Claude and edited by Melumi11
# This optional script is intended to be run manually from the root of the server directory, not from the world directory. It will navigate into the world directory to perform operations, then return.
# The server owner may manually run this script or call it from the server startup script to manually reset the world between games. I recommend running it after a few games to reset the end and reduce the world size.

# Death Swap - Clear World Chunks and Reset Seed
# Keeps lobby chunks (region 0,0 and adjacent), clears gameplay-generated chunks
# IMPORTANT: Server must be stopped before running this script

set -e

WORLD_DIR="world"
FINAL_DIR=".."
cd "$WORLD_DIR"

echo "=== Death Swap World Reset ==="
echo ""
echo "This script will:"
echo "  • Keep overworld lobby chunks (center spawn area)"
echo "  • Delete all other overworld chunks"
echo "  • Delete all nether chunks"
echo "  • Delete all end chunks"
echo "  • Generate a new world seed"
echo ""
echo "The server must be completely stopped before running this."
echo ""

# Check if server is running
if pgrep -f "java.*server" > /dev/null; then
    echo "ERROR: Server appears to be running. Please stop the server first."
    echo "Chunks and level.dat are locked while the server is active."
    exit 1
fi

# Optional: Create a backup before clearing (uncomment if desired)
# echo "Creating backup to backups/world_backup_$(date +%Y%m%d_%H%M%S)..."
# mkdir -p "backups"
# cp -r "dimensions" "backups/world_backup_$(date +%Y%m%d_%H%M%S)" 2>/dev/null || true

# Lobby region chunks to preserve (spawn area at 0,0)
LOBBY_REGIONS=("r.0.0.mca" "r.0.-1.mca" "r.-1.0.mca" "r.-1.-1.mca")
LOBBY_POI=("r.0.0.mca" "r.0.-1.mca" "r.0.-2.mca" "r.0.1.mca" "r.-1.0.mca" "r.-1.-1.mca" "r.-1.-2.mca" "r.-1.1.mca" "r.1.0.mca" "r.1.-1.mca" "r.1.-2.mca" "r.1.1.mca")

echo ""
echo "Clearing overworld..."
# Delete all overworld region files except lobby
if [ -d "dimensions/minecraft/overworld/region" ]; then
    for file in dimensions/minecraft/overworld/region/*.mca; do
        filename=$(basename "$file")
        if [[ ! " ${LOBBY_REGIONS[@]} " =~ " ${filename} " ]]; then
            rm -f "$file"
        fi
    done
    echo "  Deleted non-lobby region files"
fi

# Delete non-lobby POI files
if [ -d "dimensions/minecraft/overworld/poi" ]; then
    for file in dimensions/minecraft/overworld/poi/*.mca; do
        filename=$(basename "$file")
        if [[ ! " ${LOBBY_POI[@]} " =~ " ${filename} " ]]; then
            rm -f "$file"
        fi
    done
    echo "  Deleted non-lobby POI files"
fi

# Delete non-lobby entity files
if [ -d "dimensions/minecraft/overworld/entities" ]; then
    for file in dimensions/minecraft/overworld/entities/*.mca; do
        filename=$(basename "$file")
        if [[ ! " ${LOBBY_POI[@]} " =~ " ${filename} " ]]; then
            rm -f "$file"
        fi
    done
    echo "  Deleted non-lobby entity files"
fi

# Clear nether
echo "Clearing nether..."
rm -f dimensions/minecraft/the_nether/region/*.mca 2>/dev/null || true
rm -f dimensions/minecraft/the_nether/poi/*.mca 2>/dev/null || true
rm -rf dimensions/minecraft/the_nether/entities 2>/dev/null || true
echo "  Deleted nether chunks"

# Clear end
echo "Clearing end..."
rm -f dimensions/minecraft/the_end/region/*.mca 2>/dev/null || true
rm -f dimensions/minecraft/the_end/poi/*.mca 2>/dev/null || true
rm -rf dimensions/minecraft/the_end/entities 2>/dev/null || true

# Reset dragon fight state
echo "  Resetting dragon fight state..."
rm -f "dimensions/minecraft/the_end/data/minecraft/ender_dragon_fight.dat" 2>/dev/null || true
rm -f "dimensions/minecraft/the_end/data/minecraft/raids.dat" 2>/dev/null || true
echo "  Dragon fight file deleted (will be regenerated by server)"
echo "  Cleared end chunks and reset dragon state"

echo ""
echo "Chunk data cleared successfully (lobby preserved)."
echo ""

# Change world seed in level.dat
echo "Changing world seed..."

# Generate a random seed (64-bit integer)
NEW_SEED=$((RANDOM * 65536 + RANDOM))

# Python script to modify world seed in world_gen_settings.dat
python3 - "$NEW_SEED" << 'EOFPYTHON'
import sys
from pathlib import Path

try:
    from nbt.nbt import NBTFile
except ImportError:
    print("Installing nbt library...")
    import subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "nbt"])
    from nbt.nbt import NBTFile

worldgen_settings_path = Path("data/minecraft/world_gen_settings.dat")

try:
    new_seed = int(sys.argv[1])

    # Read the world gen settings NBT file
    settings = NBTFile(filename=str(worldgen_settings_path))

    # Update the seed (it's nested under 'data')
    if 'data' in settings:
        if 'seed' in settings['data']:
            settings['data']['seed'].value = new_seed
            print(f"Successfully changed world seed to: {new_seed}")
        else:
            print(f"Available keys in data: {list(settings['data'].keys())}")
            raise KeyError("seed not found in data")
    else:
        raise KeyError("data tag not found in world_gen_settings.dat")

    # Write back
    settings.write_file(filename=str(worldgen_settings_path))

except Exception as e:
    print(f"Error modifying world seed: {e}")
    print("Seed may need manual modification.")
    sys.exit(1)

EOFPYTHON

if [ $? -eq 0 ]; then
    echo "World seed updated successfully."
else
    echo "WARNING: Failed to update world seed. Chunks were cleared but seed remains the same."
fi

echo ""
echo "=== Reset Complete ==="
echo "✓ Overworld lobby preserved"
echo "✓ Gameplay chunks deleted"
echo "✓ Nether and end cleared"
echo "✓ Dragon fight state reset"
echo "✓ New world seed generated"
echo "Server is ready to restart."
echo ""

# Return to original directory
cd "$FINAL_DIR"
