package com.deathswap.util;

import java.util.Map;

/**
 * Central English-to-Chinese (中文) lookup for every user-facing string in the
 * mod — the {@code announce(...)} broadcast verbs and per-effect chat/title
 * lines in {@link com.deathswap.items.ItemRegistry} /
 * {@link com.deathswap.items.ItemManager}, the game-flow titles, deaths and
 * countdown text in {@link com.deathswap.game.Messages}, the scoreboard
 * labels, and the per-item display names shown on the offered dyes. Chinese
 * strings are taken verbatim from the original datapack
 * ({@code Lang Core} 2) where it provided one, and authored to match the same
 * wording/tone where it did not.
 *
 * <p>Lookups are keyed on the exact English string used at the call site, so the
 * English literal stays the source of truth and {@link #translate} falls back to
 * it when no translation exists. Interpolated messages (those with a player name
 * or number spliced into the middle) translate their literal fragments here and
 * keep the concatenation at the call site.
 */
public final class Translator {

    private Translator() {
    }

    /** Returns the Chinese string for {@code en} when {@code zh}, else {@code en}. */
    public static String translate(boolean zh, String en) {
        return zh ? ZH.getOrDefault(en, "Failed to translate to ZH: " + en) : en;
    }

    private static final Map<String, String> ZH = Map.ofEntries(
            // ---- announce(...) verbs (target name, if any, is appended after) ----
            Map.entry("Gave extremely fast, un-navigable speed to", "给予了快到无法操控的速度:"),
            Map.entry("Teleported to the End dimension:", "传送到了末地维度:"),
            Map.entry("Made the swap happen right NOW!", "立即触发了一次交换!"),
            Map.entry("Teleported far, far away:", "传送到了很远很远的地方:"),
            Map.entry("Teleported to the middle of an ocean:", "传送到了海洋中央:"),
            Map.entry("Disabled the jump of", "禁用了跳跃能力:"),
            Map.entry("Spawned ignited TNT on", "在其身上生成了点燃的TNT:"),
            Map.entry("Placed a 7x7x7 cube of air, deleting all blocks on", "放置了一个7x7x7的空气立方体, 删除了其周围所有方块:"),
            Map.entry("Teleported to Y = -60 (bedrock layer):", "传送到了 Y = -60 (基岩层):"),
            Map.entry("Trapped in an annoying barrier block cage:", "把其困在了一个恼人的屏障方块笼子里:"),
            Map.entry("Gave motion sickness to", "让其感到晕车:"),
            Map.entry("Changed all nearby blocks to stone for", "把附近所有方块变成了石头:"),
            Map.entry("Put a curse-of-binding leather tunic on", "给其穿上了一件绑定诅咒的皮革外套:"),
            Map.entry("Made a bedrock trail follow", "让一条基岩小径跟随着:"),
            Map.entry("Gave blindness & darkness to", "给予了失明与黑暗:"),
            Map.entry("Spawned falling anvils above", "在其头顶生成了下落的铁砧:"),
            Map.entry("Put into adventure mode for 40 seconds:", "让其进入冒险模式40秒:"),
            Map.entry("Replaced all air around with bells for", "把其周围的空气都替换成了钟:"),
            Map.entry("Spawned a layer of lava above", "在其头顶生成了一层岩浆:"),
            Map.entry("Summoned a horde of bees around", "在其周围召唤了一大群蜜蜂:"),
            Map.entry("Teleported to", "传送到了:"),
            Map.entry("Struck with lightning:", "用闪电劈了:"),
            Map.entry("Put a pumpkin head on", "给其戴上了一个南瓜头:"),
            Map.entry("Drowned with a flood of water:", "用洪水淹没了:"),
            Map.entry("Made extremely tiny:", "把其变得非常迷你:"),
            Map.entry("Made extremely huge:", "把其变得非常巨大:"),
            Map.entry("Placed a layer of gravel above everyone else", "在其他所有人的头顶放置了一层沙砾"),
            Map.entry("Reduced the time between swaps by 30 seconds", "把交换之间的间隔缩短了30秒"),
            Map.entry("Blocked out the sun with an obsidian ceiling for", "用黑曜石天花板挡住了阳光:"),
            Map.entry("Filled the inventory with useless junk:", "用一堆没用的垃圾塞满了物品栏:"),
            Map.entry("Turned the world into the Nether around", "把其周围的世界变成了下界:"),
            Map.entry("Placed a bunch of cobwebs on", "在其身上放置了一堆蜘蛛网:"),
            Map.entry("Summoned a California-level earthquake on the world", "在世界上召唤了一场加州级别的大地震"),
            Map.entry("Blocked item usage for", "禁止其使用物品:"),
            Map.entry("Forced a downward look for 45 seconds:", "强制其向下看了45秒:"),
            Map.entry("Bombarded with a heck-ton of ghasts:", "用成吨的恶魂轰炸了:"),
            Map.entry("Trapped inside of a prison:", "把其关进了一座监狱里:"),
            Map.entry("Liquidated all nearby blocks into water:", "把附近所有方块都变成了水:"),
            Map.entry("Set the time to midnight", "把时间设置为午夜"),
            Map.entry("Set the time to day", "把时间设置为白天"),
            Map.entry("Spawned a giant slime on", "在其身上生成了一只巨型史莱姆:"),
            Map.entry("Removed 2 hearts from", "移除了2颗心:"),
            Map.entry("Ambushed with a Viet Cong attack:", "用越共式伏击突袭了:"),
            Map.entry("Set the difficulty to hard!", "把游戏难度设置为困难模式!"),
            Map.entry("Set the difficulty to normal", "把游戏难度设置为普通模式"),
            Map.entry("Set the difficulty to easy", "把游戏难度设置为简单模式"),
            Map.entry("Teleported to a superflat world:", "传送到了一个超平坦世界:"),
            Map.entry("Crashed the Minecraft game of", "让其Minecraft游戏崩溃了:"),
            Map.entry("Turned keep_inventory BACK ON!", "重新开启了游戏规则'保留物品栏'!"),
            Map.entry("Turned keep_inventory OFF!", "关闭了游戏规则'保留物品栏'!"),
            Map.entry("Put into spectator mode for 20 seconds:", "让其进入旁观者模式20秒:"),
            Map.entry("Re-shuffled everybody around the world except themself!", "把除自己以外的所有人在世界各地重新打乱了!"),
            Map.entry("Turned natural_regeneration BACK ON!", "重新开启了游戏规则'自然再生'!"),
            Map.entry("Turned natural_regeneration OFF!", "关闭了游戏规则'自然再生'!"),
            Map.entry("Built a Quartz maze around", "在其周围建造了一座石英迷宫:"),
            Map.entry("Turned all nearby blocks to obsidian for", "把附近所有方块变成了黑曜石:"),
            Map.entry("Deleted the chunk standing in:", "删除了其所站立的区块:"),
            Map.entry("Switched places with", "和其交换了位置:"),
            Map.entry("Turned the game into a low-gravity environment", "把游戏变成了低重力环境"),
            Map.entry("Made the ears bleed for 45 seconds:", "让其耳朵流血了45秒:"),
            Map.entry("Spawned inside of Parkour Civilization:", "把其传送进了跑酷文明:"),
            Map.entry("Blocked crafting tables & furnaces for", "禁止其使用工作台和熔炉:"),
            Map.entry("Summoned a Giant zombie on", "在其身上召唤了一只巨人僵尸:"),
            Map.entry("Made continuously pee for 1 minute:", "让其持续尿尿了1分钟:"),
            Map.entry("Summoned the Warden on", "在其身上召唤了监守者:"),
            Map.entry("Teleported directly to the Nether:", "把其直接传送到了下界:"),
            Map.entry("Summoned the Oppenheimer nuclear bomb on", "在其身上召唤了奥本海默核弹:"),
            Map.entry("Set everything on fire around", "点燃了其周围的一切:"),
            Map.entry("Jumpscared", "惊吓了:"),
            Map.entry("Spawned 100 villagers at", "在其位置生成了100个村民:"),
            Map.entry("Spawned 100 Endermen at", "在其位置生成了100个末影人:"),
            Map.entry("Spawned 20 chicken jockeys on", "在其身上生成了20只鸡骑师:"),

            // ---- per-effect chat / title lines ----
            Map.entry("A gravel tower was placed right in front of you!", "一座碎石堆砌的塔就矗立在你面前!"),
            Map.entry("You can't jump: 1 minute", "你无法跳跃: 1分钟"),
            Map.entry(">> A nether portal was placed in front of you! <<", ">> 一个下界传送门出现在你面前! <<"),
            Map.entry("RUN away!", "逃跑!"),
            Map.entry(">> A hole to the void summoned in front of you! <<", ">> 一个通往虚空的洞口在你面前出现! <<"),
            Map.entry(">>> You are in CREATIVE MODE for 10 seconds! <<<", ">>> 你将进入创造模式10秒! <<<"),
            Map.entry("Look below you!", "看看你的下方!"),
            Map.entry(">> HEADS UP!! <<", ">> 小心!! <<"),
            Map.entry(">> You're in adventure mode for 40 secs! <<", ">> 你已进入冒险模式, 持续40秒! <<"),
            Map.entry(">> You are very smol! <<", ">> 你变得非常迷你! <<"),
            Map.entry(">> You are very beeg! <<", ">> 你变得非常巨大! <<"),
            Map.entry("You now have access to a village! (IMPORTANT: If you are underground, it spawned up on the surface!)",
                    "你现在可以使用一个村庄了! (重要提示: 如果你在地下, 它生成在了地表上!)"),
            Map.entry("You now have access to a desert temple/pyramid! Good job!",
                    "你现在可以使用一座沙漠神殿/金字塔了! 干得好!"),
            Map.entry(">> You can use items again!!! <<", ">> 你可以再次使用物品了!!! <<"),
            Map.entry(">> You can't use items for 3 minutes! <<", ">> 你在三分钟内无法使用任何物品! <<"),
            Map.entry(">> The world has finished transforming into the Nether! <<", ">> 世界已完成向下界的转变! <<"),
            Map.entry("+4 Hearts!", "+4 颗心!"),
            Map.entry("You placed an Amethyst Geode", "你放置了一个紫水晶洞"),
            Map.entry("You built a Stalagmite trap in front of you!", "你在你面前建造了一个石笋陷阱!"),
            Map.entry("3x Faster mining: 120 seconds", "挖矿速度提升3倍: 120秒"),
            Map.entry(">> NO FALL DAMAGE! 5 Mins <<", ">> 无坠落伤害! 5分钟 <<"),
            Map.entry(">> YOU CAN'T HEAR ANYTHING! 45 secs <<", ">> 你什么都听不见了! 45秒 <<"),
            Map.entry("You can't use crafting tables & furnaces: 90 secs!", "你不能使用工作台和熔炉: 90秒!"),
            Map.entry(">> Forcefield: 3 minutes! <<", ">> 力场: 3分钟! <<"),
            Map.entry(">> A Woodland Mansion was built near you!", ">> 你附近建造了一座林地府邸!"),
            Map.entry("You are peeing...", "你正在尿尿..."),
            Map.entry(">> warden.. <<", ">> 监守者.. <<"),
            Map.entry("Your game will lag heavily!", "你的游戏将严重卡顿!"),
            Map.entry(">>> WARNING!! <<<", ">>> 警告!! <<<"),
            Map.entry("Explodes in 12 secs -- RUN!!", "12秒后爆炸 -- 快跑!!"),
            Map.entry(">> NUKE!!! <<", ">> 核弹!!! <<"),
            Map.entry("> Go down the ladder to reach the stronghold! (It's around y = at 30)",
                    "> 顺着梯子下去就能到达要塞! (大约在 y = 30 处)"),
            Map.entry("> Go down the ladder and you'll find the Trial Chamber! (It's around y = at 30)",
                    "> 顺着梯子下去, 就能找到审判室! (大约在 y = 30 处)"),
            Map.entry("> Go down the ladder and you'll find the Ancient City! (May not have spawned if in the Nether or the End!)",
                    "> 顺着梯子下去, 你就会发现那座古城! (如果你身处下界或末地, 它可能不会生成!)"),
            Map.entry("Your shield wore off. Others can target you again.", "你的护盾已失效, 其他人可以再次将你作为目标了。"),
            Map.entry(">> The earthquake has concluded! You are safe now! <<", ">> 地震已经结束! 你现在安全了! <<"),
            Map.entry("The Việt Cộng", "越共"),
            Map.entry("One-hit-kill -- ONE USE!", "一击必杀 -- 仅限一次使用!"),
            Map.entry("CHICKEN JOCKEYYYYYY", "鸡骑师!!!!!!!"),

            // ---- interpolated item messages (player name/number spliced at call site) ----
            Map.entry("Powerup slot — items appear here", "能力物品栏 — 物品会出现在这里"),
            Map.entry("Given item #", "已给予物品 #"),
            Map.entry(") -- drop it to use.", ") -- 丢出以使用."),
            Map.entry("** You can't use items right now!", "** 你现在无法使用物品!"),
            Map.entry("\n>> Click on which player you want to use this item on: ", "\n>> 点击你想对哪个玩家使用此物品: "),
            Map.entry(" is/are shielded from items!", " 对物品免疫!"),
            Map.entry(">> That player can't be targeted. <<", ">> 无法以该玩家为目标。 <<"),
            Map.entry(" cleared your inventory!", " 清空了你的物品栏!"),
            Map.entry(" --> Cleared ", " --> 清空了 "),
            Map.entry("'s inventory! (randomly chosen)", " 的物品栏! (随机选中)"),
            Map.entry(">>> IMPORTANT: You can't use ANY items for 3 minutes because ",
                    ">>> 重要提示: 你在三分钟内无法使用任何物品, 因为 "),
            Map.entry(" used an item on you! <<<", " 对你使用了一个物品! <<<"),
            Map.entry(" shielded themself from negative items! <<", " 用屏障保护自己免受负面物品的影响! <<"),
            Map.entry(" can't see you!", " 看不到你!"),

            // ---- game-flow text (titles, deaths, swap countdown) ----
            Map.entry(">> Swapped! <<", ">> 球员互换! <<"),
            Map.entry("* You warped to: ", "* 你已传送到: "),
            Map.entry(">> D.S. But Way Better! <<", ">> 死亡交换, 但更棒! <<"),
            Map.entry("Created by Jerries!", "由 Jerries 制作!"),
            Map.entry("Map created by Jerries", "地图由 Jerries 制作"),
            Map.entry(" (Map version 1.0.3)", " (地图版本 1.0.3)"),
            Map.entry("Additional datapack work by TheWorfer27 and Melumi11", "额外数据包制作: TheWorfer27 和 Melumi11"),
            Map.entry(">> Spreading players... <<", ">> 球员搬迁... <<"),
            Map.entry(" > DIED! Lost a life!", " > 死亡了! 失去一条生命!"),
            Map.entry(">> YOU DIED! <<", ">> 你死了! <<"),
            Map.entry("-1 Life!", "-1 生命!"),
            Map.entry(">> ELIMINATED! <<", ">> 被淘汰! <<"),
            Map.entry(" Won! <<", " 获胜了! <<"),
            Map.entry("They survived the way better death swap!", "他们在更精彩的死亡交换游戏中获胜了!"),
            Map.entry(" survived the longest and won the game! <<<\n", " 获得了最高分，赢得了比赛! <<<\n"),
            Map.entry(" joined the server mid-game and will spectate until the game is over!",
                    " 在游戏中途加入了服务器, 将以旁观者身份观战直到本局游戏结束!"),
            Map.entry("You will spectate", "你将作为旁观者"),
            Map.entry("Until this game finishes!", "直到本局游戏结束!"),
            Map.entry("LANGUAGE: English!", "语言：中文!"),
            Map.entry("Language: English", "语言：中文"),
            Map.entry(">> New items! <<", ">> 你获得了新物品! <<"),
            Map.entry("<< You got a new set of items! They will expire in 45 seconds if you don't use one of them! You can only use one! >>",
                    "<< 你获得了一套新的物品! 如果您不使用其中任何一个，它们将在 45 秒后失效! >>"),
            Map.entry("** Items blocked!", "** 物品已被封锁!"),
            Map.entry(">> Swapping <<", ">> 交换中 <<"),
            Map.entry("In 1 minute", "1分钟后"),
            Map.entry("In 30 seconds", "30秒后"),
            Map.entry("In 10 seconds", "10秒后"),
            Map.entry("In 5", "还有 5"),
            Map.entry("In 4", "还有 4"),
            Map.entry("In 3", "还有 3"),
            Map.entry("In 2", "还有 2"),
            Map.entry("In 1", "还有 1"),
            Map.entry("In ", "还有 "),

            // ---- scoreboard labels ----
            Map.entry("Lives", "生命"),
            Map.entry("Health", "生命值"),
            Map.entry("Wins", "胜场"),

            // ---- item display names (datapack ch_detect_item; item LORE is NOT translated) ----
            Map.entry("Give a player speed 1 billion: 40 secs", "赋予玩家速度10亿：40秒"),
            Map.entry("Give yourself materials to build a wither", "给自己一些材料来建造一个凋灵"),
            Map.entry("Shield yourself from negative items: 2 mins", "保护自己免受负面物品的影响：2分钟"),
            Map.entry("Teleport someone to the End", "将随机一人传送到末地"),
            Map.entry("Swap all players right NOW!", "立即交换所有玩家!"),
            Map.entry("Teleport someone really far away", "把某人传送到很远的地方"),
            Map.entry("Give yourself a super fast shovel", "给自己一把超快的铲子"),
            Map.entry("Spawn 100 villagers on someone", "在某人身上生成100villagers个村民"),
            Map.entry("Summon an 300 block-tall gravel tower", "召唤一座300格高的沙砾塔"),
            Map.entry("Teleport someone to the middle of the ocean", "将某人传送到海洋中央"),
            Map.entry("Disable a player's ability to jump: 60 secs", "禁用玩家的跳跃能力：60秒"),
            Map.entry("Place a Nether Portal next to you", "在你旁边放置一个下界传送门"),
            Map.entry("Give yourself 32 steak", "给自己32块牛排steak"),
            Map.entry("Spawn TNT on someone", "在某人身上生成TNT炸药"),
            Map.entry("Place a 7x7x7 cube of air on someone", "把一个7x7x7立方体的空气放在某人身上"),
            Map.entry("Teleport someone to y= -60", "将某人传送到 y = -60 的位置"),
            Map.entry("Spawn a hole that goes to the void", "生成一个通往虚空的洞"),
            Map.entry("Enter creative mode for 10 seconds", "进入创意模式creative mode 10秒钟"),
            Map.entry("Give yourself 4 pieces of TNT", "给自己四个TNT炸药块"),
            Map.entry("Trap a player in a barrier block cage", "把某人关进用障碍方块搭建的笼子里"),
            Map.entry("Give a player motion sickness: 30 seconds", "让玩家感到晕晕车：30秒"),
            Map.entry("Turn all nearby blocks of a player to stone", "将玩家附近的所有方块变成石头"),
            Map.entry("Put a curse of binding leather chestplate on someone", "对某人施加束缚皮甲的诅咒leather chestplate"),
            Map.entry("/clear a RANDOM person's inventory (could be you!!)", "/clear清空一名随机玩家的物品栏(也可能是你!!)"),
            Map.entry("Make someone leave a bedrock trail: 40 secs", "让某人留下基岩痕迹：40秒"),
            Map.entry("Give someone blindness & darkness: 40 secs", "某人失明并陷入黑暗：40秒"),
            Map.entry("Give yourself one ravager spawn egg", "给自己一个掠夺者生ravager spawn egg"),
            Map.entry("Give yourself an elytra & fireworks", "给自己一套鞘翅和烟花"),
            Map.entry("Give yourself a milk bucket & 2 golden apples", "给自己一milk bucket个牛奶桶来清除效果"),
            Map.entry("Give yourself a fire resistance potion", "给自己一瓶防火药水"),
            Map.entry("Shield yourself from negative items: 3 mins", "保护自己免受负面事物的影响：3分钟"),
            Map.entry("Spawn falling anvils above someone", "anvils在某人上方生成掉落的铁砧"),
            Map.entry("Put someone in adventure mode: 40 secs", "让某人进入冒险模式adventure mode:40秒"),
            Map.entry("Place bells all around someone", "在某人周围放置铃铛"),
            Map.entry("Place a layer of lava above someone", "在某人上方放置一层熔岩"),
            Map.entry("Spawn a horde of bees around someone", "在某人周围召唤一大群蜜蜂"),
            Map.entry("Give yourself full diamond armor & tools", "给自己一套完整的钻石盔甲和工具"),
            Map.entry("Teleport to someone (& surprise attack them?)", "传送到某人身边（然后发动突袭?)"),
            Map.entry("Give yourself 9 obsidian", "给自己9个黑曜石"),
            Map.entry("Strike someone with lightning", "用闪电击中某人"),
            Map.entry("Put a pumpkin head on someone: 1 min", "给某人戴上南瓜头：1分钟"),
            Map.entry("Drown someone with a flood of water", "用洪水淹死某人"),
            Map.entry("Make someone extremely tiny", "把某人变得非常小"),
            Map.entry("Make someone extremely huge", "让某人变得极其巨大"),
            Map.entry("Give yourself a totem of undying", "给自己一个永生图腾totem of undying"),
            Map.entry("Place a layer of gravel above EVERYONE except you", "除了你之外, gravel在每个人上方都铺上一层碎石"),
            Map.entry("Make the swap cycle length 30 seconds shorter", "swap将交换周期缩短30秒"),
            Map.entry("Block out the sun for someone", "为某人遮挡阳光"),
            Map.entry("Fill up someone's inventory with junk", "用垃圾填满某人的物品栏"),
            Map.entry("Transform the world around someone into the Nether", "把某人周围的世界变成下界nether"),
            Map.entry("Spawn a bunch of cobwebs on someone", "在某人身上生成一大堆蜘蛛cobwebs网"),
            Map.entry("Give yourself 3 ender pearls", "给自己三个末影珍珠"),
            Map.entry("Spawn a village right where you are", "village在你当前位置生成一个村庄"),
            Map.entry("Spawn a desert temple right where you are", "在你当前位置生成一座沙漠神庙"),
            Map.entry("Summon a California earthquake on EVERYONE except you", "召唤一California场加州地震，但除了你之外，其他人都会受到影响"),
            Map.entry("Block someone from using any items: 3 mins", "禁止某人使用任何物品：3分钟"),
            Map.entry("Give yourself an enchanted golden apple", "给自己一个附魔金苹果"),
            Map.entry("Force a player to look down for 45 secs", "强制玩家低头45秒"),
            Map.entry("Bombard someone with a ton of ghasts", "用大量的恶魂轰炸某人"),
            Map.entry("Jumpscare someone", "吓唬某人"),
            Map.entry("Lock someone into a prison", "把某人关进监狱"),
            Map.entry("Give yourself a water bucket", "给自己一桶水"),
            Map.entry("Give yourself a lava bucket", "给自己一桶熔岩"),
            Map.entry("Give yourself a long fire resistance potion", "给自己一瓶长时间的防火药水"),
            Map.entry("Liquidate all blocks surrounding a player", "将玩家周围的所有方块变成水"),
            Map.entry("Set time to midnight (or mid-day if it's night)", "将时间设置为午夜 (如果是晚上, 则设置为中午)"),
            Map.entry("Spawn a giant slime on someone", "在某人身上生成一个巨大的史莱姆"),
            Map.entry("Give yourself 4 extra hearts for health", "给自己增加 4 点生命值"),
            Map.entry("Take away 2 hearts from someone (leave them w/8)", "从某人身上夺走两颗心 (只剩下8个)"),
            Map.entry("Launch a Viet Cong ambush on someone", "Viet Cong召唤越共伏击某人"),
            Map.entry("Give yourself a one-hit-kill sword", "给自己一把一击必杀的剑"),
            Map.entry("Switch game's language to Chinese 中文", "将游戏语言切换为英语 English!"),
            Map.entry("Set /difficulty to hard", "将游戏难/度设置为困难"),
            Map.entry("Set /difficulty to normal", "将游戏难/度设置为普通"),
            Map.entry("Set /difficulty to easy", "将游戏难/度设置为简单"),
            Map.entry("Teleport someone to a superflat world", "将某人传送到一个超平坦世界"),
            Map.entry("Give yourself a crafting table, furnace, & materials", "给自己一个工作台和熔炉"),
            Map.entry("Crash somebody's Minecraft game", "让别人的Minecraft游戏崩溃"),
            Map.entry("Turn OFF Keep Inventory (or ON if it's off)", "关闭'保留物品栏' (如果已关闭, 则将其打开)"),
            Map.entry("Put someone into spectator mode: 20 secs", "将某人设置为旁观者模式：20秒"),
            Map.entry("Re-shuffle everyone around the world EXCEPT YOU", "重新排列全世界所有人的顺序, 除了你"),
            Map.entry("Place an Amethyst Geode where you are", "在你所在的地方放置一块紫水晶晶洞"),
            Map.entry("Turn OFF /gamerule natural regeneration (or ON if it's off)", "关闭 /gamerule 自然再生 (如果已关闭则开启)"),
            Map.entry("Build a Quartz maze around someone", "在某人周围建造一个石英迷宫"),
            Map.entry("Turn all blocks near someone to obsidian", "将某人附近的所有方块都变成黑曜石"),
            Map.entry("Build a Stalagmite trap next to you", "在你旁边建造一个石笋陷阱"),
            Map.entry("Delete the Chunk someone's standing in", "删除玩家所在的 Minecraft 区块"),
            Map.entry("Switch places with someone", "与某人交换位置"),
            Map.entry("Mine blocks faster for 90 seconds", "地雷方块移动速度提升3倍, 持续90秒"),
            Map.entry("Make the game low-gravity: 3 minutes", "将游戏设置为低重力模式: 3 分钟"),
            Map.entry("Take NO fall damage for the next 5 minutes", "接下来的5分钟内不会受到任何坠落伤害"),
            Map.entry("Make someone's ears bleed (HEADPHONE WARNING!)", "对着某人播放极其响亮的声音 (声音警告!)"),
            Map.entry("Summon a Stronghold below you", "在你下方召唤一个地下城要塞"),
            Map.entry("Give yourself a flint & steel & iron ingot", "给自己准备一块打火石和钢片"),
            Map.entry("Put someone into Parkour Civilization (from Youtube)", "把某人送入跑酷文明 (from Youtube)"),
            Map.entry("Secretly spy on what someone's currently doing", "秘密监视某人的所作所为"),
            Map.entry("Shield yourself from negative items: 2.5 mins", "避免负面影响：2.5分钟"),
            Map.entry("Block someone from using crafting tables: 90 sec", "阻止他人使用工作台：90 秒"),
            Map.entry("Gain a monster-proof forcefield: 3 mins", "获得一个能抵御怪物的力场：3分钟"),
            Map.entry("Spawn a Giant zombie on someone", "在某人身上召唤一个巨型僵尸"),
            Map.entry("Place a Trial Chamber below you", "在你的下方放置一个试炼密室"),
            Map.entry("Build a Woodland Mansion where you are", "在你当前位置建造一座林地府邸"),
            Map.entry("Make someone continuously pee: 1 min", "让人持续排尿: 1分钟"),
            Map.entry("Get an enchanting table, lapis, & XP", "获取附魔台, 青金石与经验值"),
            Map.entry("Summon the Warden on someone", "对某人召唤典狱官"),
            Map.entry("Teleport someone directly to the Nether", "将某人直接传送到下界"),
            Map.entry("Summon Oppenheimer's NUCLEAR bomb on someone", "Oppenheimer对某人召唤奥本海默的核弹"),
            Map.entry("Summon an Ancient City below you", "在你下方建造一座古城"),
            Map.entry("Set everything around someone on fire", "将某人周围的一切付之一炬"),
            Map.entry("Spawn 100 Endermen on someone", "在某人身边生成 100 只末影人"),
            Map.entry("Spawn 20 chicken jockeys on someone", "在某人身上生成20只鸡骑师"));
}
