package com.deathswap.util;

import java.util.Map;

/**
 * Central English-to-Dutch (Nederlands) lookup for every user-facing string in the
 * mod — the {@code announce(...)} broadcast verbs and per-effect chat/title
 * lines in {@link com.deathswap.items.ItemRegistry} /
 * {@link com.deathswap.items.ItemManager}, the game-flow titles, deaths and
 * countdown text in {@link com.deathswap.game.Messages}, the scoreboard
 * labels, and the per-item display names shown on the offered dyes. Dutch
 * strings are taken verbatim from the original datapack
 * ({@code Lang Core} 2) where it provided one, and authored to match the same
 * wording/tone where it did not.
 *
 * <p>Lookups are keyed on the exact English string used at the call site, so the
 * English literal stays the source of truth and {@link #translate} falls back to
 * it when no translation exists. Interpolated messages (those with a player name
 * or number spliced into the middle) translate their literal fragments here and
 * keep the concatenation at the call site.
 */
public final class Translator {

    private Translator() {
    }

    /** Returns the Dutch string for {@code en} when {@code nl}, else {@code en}. */
    public static String translate(boolean nl, String en) {
        return nl ? NL.getOrDefault(en, "Failed to translate to NL: " + en) : en;
    }

    private static final Map<String, String> NL = Map.ofEntries(
            // ---- announce(...) verbs (target name, if any, is appended after) ----
            Map.entry("Gave extremely fast, un-navigable speed to", "Gaf extreem snelle, onnavigeerbare snelheid aan"),
            Map.entry("Teleported to the End dimension:", "Geteleporteerd naar de Einderdimensie:"),
            Map.entry("Made the swap happen right NOW!", "Liet de wissel NU plaatsvinden!"),
            Map.entry("Teleported far, far away:", "Geteleporteerd naar heel ver weg:"),
            Map.entry("Teleported to the middle of an ocean:", "Geteleporteerd naar het midden van een oceaan:"),
            Map.entry("Disabled the jump of", "Uitgeschakeld het springen van"),
            Map.entry("Spawned ignited TNT on", "Ontstoken TNT gespawnd op"),
            Map.entry("Placed a 7x7x7 cube of air, deleting all blocks on", "Plaatste een 7x7x7 kubus van lucht, verwijderde alle blokken van"),
            Map.entry("Teleported to Y = -60 (bedrock layer):", "Geteleporteerd naar Y = -60 (bedrocklaag):"),
            Map.entry("Trapped in an annoying barrier block cage:", "Opgesloten in een vervelende barrièreblokkooi:"),
            Map.entry("Gave motion sickness to", "Gaf reisziekte aan"),
            Map.entry("Changed all nearby blocks to stone for", "Veranderde alle nabijgelegen blokken in steen voor"),
            Map.entry("Put a curse-of-binding leather tunic on", "Deed een vloek-van-binding lederen tuniek aan op"),
            Map.entry("Made a bedrock trail follow", "Liet een bedrockspoor achter bij"),
            Map.entry("Gave blindness & darkness to", "Gaf blindheid en duisternis aan"),
            Map.entry("Spawned falling anvils above", "Liet vallende aambeelden spawnen boven"),
            Map.entry("Put into adventure mode for 40 seconds:", "Zette in avonturenmodus voor 40 seconden:"),
            Map.entry("Replaced all air around with bells for", "Verving alle lucht rondom met klokken voor"),
            Map.entry("Spawned a layer of lava above", "Plaatste een laag lava boven"),
            Map.entry("Summoned a horde of bees around", "Summonede een zwerm bijen rondom"),
            Map.entry("Teleported to", "Geteleporteerd naar:"),
            Map.entry("Struck with lightning:", "Getroffen door bliksem:"),
            Map.entry("Put a pumpkin head on", "Zette een pompoenhoofd op"),
            Map.entry("Drowned with a flood of water:", "Verdronken met een vloed water:"),
            Map.entry("Made extremely tiny:", "Maakte extreem klein:"),
            Map.entry("Made extremely huge:", "Maakte extreem groot:"),
            Map.entry("Placed a layer of gravel above everyone else", "Plaatste een laag grind boven iedereen anders"),
            Map.entry("Reduced the time between swaps by 30 seconds", "Verkort de tijd tussen wissels met 30 seconden"),
            Map.entry("Blocked out the sun with an obsidian ceiling for", "Blokkeerde de zon met een obsidiaanplafond voor"),
            Map.entry("Filled the inventory with useless junk:", "Vulde de inventaris met waardeloos afval:"),
            Map.entry("Turned the world into the Nether around", "Veranderde de wereld rondom in de Nether:"),
            Map.entry("Placed a bunch of cobwebs on", "Plaatste een hoop spinnenweb op"),
            Map.entry("Summoned a California-level earthquake on the world", "Veroorzaakte een aardbeving op Californisch niveau"),
            Map.entry("Blocked item usage for", "Blokkeerde voorwerpgebruik voor"),
            Map.entry("Forced a downward look for 45 seconds:", "Dwong naar beneden te kijken voor 45 seconden:"),
            Map.entry("Bombarded with a heck-ton of ghasts:", "Bombardeerde met een hoop ghasts:"),
            Map.entry("Trapped inside of a prison:", "Opgesloten in een gevangenis:"),
            Map.entry("Liquidated all nearby blocks into water:", "Veranderde alle nabijgelegen blokken in water:"),
            Map.entry("Set the time to midnight", "Stelde de tijd in op middernacht"),
            Map.entry("Set the time to day", "Stelde de tijd in op dag"),
            Map.entry("Spawned a giant slime on", "Spawnte een reuzensleim op"),
            Map.entry("Removed 2 hearts from", "Verwijderde 2 harten van"),
            Map.entry("Ambushed with a Viet Cong attack:", "Aangevallen met een Viet Cong hinderlaag:"),
            Map.entry("Set the difficulty to hard!", "Stelde de moeilijkheidsgraad in op hard!"),
            Map.entry("Set the difficulty to normal", "Stelde de moeilijkheidsgraad in op normaal"),
            Map.entry("Set the difficulty to easy", "Stelde de moeilijkheidsgraad in op gemakkelijk"),
            Map.entry("Teleported to a superflat world:", "Geteleporteerd naar een superplatte wereld:"),
            Map.entry("Crashed the Minecraft game of", "Liet het Minecraft-spel crashen van"),
            Map.entry("Turned keep_inventory BACK ON!", "Zette keep_inventory WEER AAN!"),
            Map.entry("Turned keep_inventory OFF!", "Zette keep_inventory UIT!"),
            Map.entry("Put into spectator mode for 20 seconds:", "Zette in toeschouwermodus voor 20 seconden:"),
            Map.entry("Re-shuffled everybody around the world except themself!", "Herschudde iedereen over de wereld behalve zichzelf!"),
            Map.entry("Turned natural_regeneration BACK ON!", "Zette natural_regeneration WEER AAN!"),
            Map.entry("Turned natural_regeneration OFF!", "Zette natural_regeneration UIT!"),
            Map.entry("Built a Quartz maze around", "Bouwde een kwartslabyrint rondom"),
            Map.entry("Turned all nearby blocks to obsidian for", "Veranderde alle nabijgelegen blokken in obsidiaan voor"),
            Map.entry("Deleted the chunk standing in:", "Verwijderde het chunk waarop gestaan wordt:"),
            Map.entry("Switched places with", "Ruilde van plaats met"),
            Map.entry("Turned the game into a low-gravity environment", "Maakte het spel een lage-zwaartekrachtomgeving"),
            Map.entry("Made the ears bleed for 45 seconds:", "Liet de oren bloeden voor 45 seconden:"),
            Map.entry("Spawned inside of Parkour Civilization:", "Geteleporteerd naar Parkour Civilization:"),
            Map.entry("Blocked crafting tables & furnaces for", "Blokkeerde gebruik van werkbanken en ovens voor"),
            Map.entry("Summoned a Giant zombie on", "Summonede een reuzenzombie op"),
            Map.entry("Made continuously pee for 1 minute:", "Liet continu plassen voor 1 minuut:"),
            Map.entry("Summoned the Warden on", "Summonede de Warden op"),
            Map.entry("Teleported directly to the Nether:", "Geteleporteerd direct naar de Nether:"),
            Map.entry("Summoned the Oppenheimer nuclear bomb on", "Summonede de Oppenheimer-kernbom op"),
            Map.entry("Set everything on fire around", "Stak alles rondom in brand voor"),
            Map.entry("Jumpscared", "Liet schrikken:"),
            Map.entry("Spawned 100 villagers at", "Spawnte 100 dorpelingen bij"),
            Map.entry("Spawned 100 Endermen at", "Spawnte 100 Endermen bij"),
            Map.entry("Spawned 3 chicken jockeys on", "Spawnte 3 kippenjockeys op"),

            // ---- per-effect chat / title lines ----
            Map.entry("A gravel tower was placed right in front of you!", "Een grinttoren staat recht voor je!"),
            Map.entry("You can't jump: 1 minute", "Je kunt niet springen: 1 minuut"),
            Map.entry(">> A nether portal was placed in front of you! <<", ">> Een Nether-portaal verscheen voor je! <<"),
            Map.entry("RUN away!", "WEGRENNEN!"),
            Map.entry(">> A hole to the void summoned in front of you! <<", ">> Een gat naar de leegte verscheen voor je! <<"),
            Map.entry(">>> You are in CREATIVE MODE for 10 seconds! <<<", ">>> Je bent 10 seconden in CREATIEVE MODUS! <<<"),
            Map.entry("Look below you!", "Kijk onder je!"),
            Map.entry(">> HEADS UP!! <<", ">> PAS OP!! <<"),
            Map.entry(">> You're in adventure mode for 40 secs! <<", ">> Je bent in avonturenmodus voor 40 sec! <<"),
            Map.entry(">> You are very smol! <<", ">> Je bent erg klein! <<"),
            Map.entry(">> You are very beeg! <<", ">> Je bent erg groot! <<"),
            Map.entry("You now have access to a village! (IMPORTANT: If you are underground, it spawned up on the surface!)",
                    "Je hebt nu toegang tot een dorp! (BELANGRIJK: Als je ondergronds bent, is het aan de oppervlakte gespawnd!)"),
            Map.entry("You now have access to a desert temple/pyramid! Good job!",
                    "Je hebt nu toegang tot een desert tempel/piramide! Goed gedaan!"),
            Map.entry(">> You can use items again!!! <<", ">> Je kunt weer voorwerpen gebruiken!!! <<"),
            Map.entry(">> You can't use items for 3 minutes! <<", ">> Je kunt 3 minuten lang geen voorwerpen gebruiken! <<"),
            Map.entry(">> The world has finished transforming into the Nether! <<", ">> De wereld is klaar met transformeren naar de Nether! <<"),
            Map.entry("+4 Hearts!", "+4 Harten!"),
            Map.entry("You placed an Amethyst Geode", "Je plaatste een Amethist Grot"),
            Map.entry("You built a Stalagmite trap in front of you!", "Je bouwde een druipsteenval voor je!"),
            Map.entry("3x Faster mining: 120 seconds", "3x Sneller minen: 120 seconden"),
            Map.entry(">> NO FALL DAMAGE! 5 Mins <<", ">> GEEN VALSCHADE! 5 Min <<"),
            Map.entry(">> YOU CAN'T HEAR ANYTHING! 45 secs <<", ">> JE KUNT NIETS HOREN! 45 sec <<"),
            Map.entry("You can't use crafting tables & furnaces: 90 secs!", "Je kunt geen werkbanken en ovens gebruiken: 90 sec!"),
            Map.entry(">> Forcefield: 3 minutes! <<", ">> Krachtschild: 3 minuten! <<"),
            Map.entry(">> A Woodland Mansion was built near you!", ">> Een Bosmanswoning werd gebouwd bij jou!"),
            Map.entry("You are peeing...", "Je bent aan het plassen..."),
            Map.entry(">> warden.. <<", ">> warden.. <<"),
            Map.entry("Your game will lag heavily!", "Je spel zal zwaar laggen!"),
            Map.entry(">>> WARNING!! <<<", ">>> WAARSCHUWING!! <<<"),
            Map.entry("Explodes in 12 secs -- RUN!!", "Explodeert in 12 sec -- RENNEN!!"),
            Map.entry(">> NUKE!!! <<", ">> KERNBOM!!! <<"),
            Map.entry("> Go down the ladder to reach the stronghold! (It's around y = at 30)",
                    "> Ga de ladder af om het Stronghold te bereiken! (Het is rond y = 30)"),
            Map.entry("> Go down the ladder and you'll find the Trial Chamber! (It's around y = at 30)",
                    "> Ga de ladder af en je vindt de Proefkamer! (Het is rond y = 30)"),
            Map.entry("> Go down the ladder and you'll find the Ancient City! (May not have spawned if in the Nether or the End!)",
                    "> Ga de ladder af en je vindt de Oude Stad! (Kan niet gespawnd zijn als je in de Nether of het Einde bent!)"),
            Map.entry("Your shield wore off. Others can target you again.", "Je schild is uitgewerkt. Anderen kunnen je weer als doel kiezen."),
            Map.entry(">> The earthquake has concluded! You are safe now! <<", ">> De aardbeving is voorbij! Je bent nu veilig! <<"),
            Map.entry("The Việt Cộng", "Viet Cong"),
            Map.entry("One-hit-kill -- ONE USE!", "Één-klap-dood -- EENMALIG GEBRUIK!"),
            Map.entry("CHICKEN JOCKEYYYYYY", "KIPPENJOCKEY!!!!"),

            // ---- interpolated item messages (player name/number spliced at call site) ----
            Map.entry("Powerup slot — items appear here", "Krachtsleuf — voorwerpen verschijnen hier"),
            Map.entry("Given item #", "Gegeven voorwerp #"),
            Map.entry(") -- drop it to use.", ") -- laat vallen om te gebruiken."),
            Map.entry("** You can't use items right now!", "** Je kunt nu geen voorwerpen gebruiken!"),
            Map.entry("\n>> Click on which player you want to use this item on: ", "\n>> Klik op welke speler je dit voorwerp wilt gebruiken: "),
            Map.entry(" is/are shielded from items!", " is beschermd tegen voorwerpen!"),
            Map.entry(">> That player can't be targeted. <<", ">> Die speler kan niet worden aangewezen. <<"),
            Map.entry(" cleared your inventory!", " leegde jouw inventaris!"),
            Map.entry(" --> Cleared ", " --> Leeggemaakt "),
            Map.entry("'s inventory! (randomly chosen)", "s inventaris! (willekeurig gekozen)"),
            Map.entry(">>> IMPORTANT: You can't use ANY items for 3 minutes because ",
                    ">>> BELANGRIJK: Je kunt 3 minuten lang geen voorwerpen gebruiken, omdat "),
            Map.entry(" used an item on you! <<<", " een voorwerp op je heeft gebruikt! <<<"),
            Map.entry(" shielded themself from negative items! <<", " zichzelf beschermde tegen negatieve voorwerpen! <<"),
            Map.entry(" can't see you!", " kan je niet zien!"),

            // ---- game-flow text (titles, deaths, swap countdown) ----
            Map.entry(">> Swapped! <<", ">> Gewisseld! <<"),
            Map.entry("* You warped to: ", "* Je bent geteleporteerd naar: "),
            Map.entry(">> D.S. But Way Better! <<", ">> D.S. Maar Veel Beter! <<"),
            Map.entry("Created by Jerries!", "Gemaakt door Jerries!"),
            Map.entry("Map created by Jerries", "Kaart gemaakt door Jerries"),
            Map.entry(" (Map version 1.0.3)", " (Kaartversie 1.0.3)"),
            Map.entry("Additional datapack work by TheWorfer27 and Melumi11", "Extra datapack werk door TheWorfer27 en Melumi11"),
            Map.entry(">> Spreading players... <<", ">> Spelers verspreiden... <<"),
            Map.entry(" > Lost a life!", " > Een leven verloren!"),
            Map.entry(">> YOU DIED! <<", ">> JE BENT DOOD! <<"),
            Map.entry("-1 Life!", "-1 Leven!"),
            Map.entry(">> ELIMINATED! <<", ">> UITGESCHAKELD! <<"),
            Map.entry(" Won! <<", " Gewonnen! <<"),
            Map.entry("They survived the way better death swap!", "Ze overleefden de veel betere death swap!"),
            Map.entry(" survived the longest and won the game! <<<\n", " overleefde het langst en won het spel! <<<\n"),
            Map.entry(" joined the server mid-game and will spectate until the game is over!",
                    " sloot zich midden in het spel aan bij de server en zal toeschouwer zijn tot het spel voorbij is!"),
            Map.entry("You will spectate", "Je zult toeschouwer zijn"),
            Map.entry("Until this game finishes!", "Totdat dit spel klaar is!"),
            Map.entry("LANGUAGE: English!", "TAAL: Engels!"),
            Map.entry("Language: English", "Taal: Engels"),
            Map.entry(">> New items! <<", ">> Nieuwe voorwerpen! <<"),
            Map.entry("<< You got a new set of items! They will expire in 45 seconds if you don't use one of them! You can only use one! >>",
                    "<< Je hebt een nieuwe set voorwerpen gekregen! Ze verlopen na 45 seconden als je er geen gebruikt! Je kunt er maar één gebruiken! >>"),
            Map.entry("** Items blocked!", "** Voorwerpen geblokkeerd!"),
            Map.entry(">> Swapping <<", ">> Aan het wisselen <<"),
            Map.entry("In 1 minute", "Over 1 minuut"),
            Map.entry("In 30 seconds", "Over 30 seconden"),
            Map.entry("In 10 seconds", "Over 10 seconden"),
            Map.entry("In 5", "Over 5"),
            Map.entry("In 4", "Over 4"),
            Map.entry("In 3", "Over 3"),
            Map.entry("In 2", "Over 2"),
            Map.entry("In 1", "Over 1"),
            Map.entry("In ", "Over "),

            // ---- scoreboard labels ----
            Map.entry("Lives", "Levens"),
            Map.entry("Health", "Gezondheid"),
            Map.entry("Wins", "Overwinningen"),

            // ---- item display names (datapack ch_detect_item; item LORE is NOT translated) ----
            Map.entry("Give a player speed 1 billion: 40 secs", "Geef een speler snelheid 1 miljard: 40 sec"),
            Map.entry("Give yourself materials to build a wither", "Geef jezelf materialen om een Wither te bouwen"),
            Map.entry("Shield yourself from negative items: 2 mins", "Bescherm jezelf tegen negatieve voorwerpen: 2 min"),
            Map.entry("Teleport someone to the End", "Teleporteer iemand naar het Einde"),
            Map.entry("Swap all players right NOW!", "Wissel alle spelers NU!"),
            Map.entry("Teleport someone really far away", "Teleporteer iemand ver weg"),
            Map.entry("Give yourself a super fast shovel", "Geef jezelf een supersnelle schop"),
            Map.entry("Spawn 100 villagers on someone", "Spawn 100 dorpelingen op iemand"),
            Map.entry("Summon an 300 block-tall gravel tower", "Roep een 300 blokken hoge grinttoren op"),
            Map.entry("Teleport someone to the middle of the ocean", "Teleporteer iemand naar het midden van de oceaan"),
            Map.entry("Disable a player's ability to jump: 60 secs", "Schakel het springen van een speler uit: 60 sec"),
            Map.entry("Place a Nether Portal next to you", "Plaats een Nether-portaal naast je"),
            Map.entry("Give yourself 32 steak", "Geef jezelf 32 biefstuk"),
            Map.entry("Spawn TNT on someone", "Spawn TNT op iemand"),
            Map.entry("Place a 7x7x7 cube of air on someone", "Plaats een 7x7x7 kubus van lucht op iemand"),
            Map.entry("Teleport someone to y= -60", "Teleporteer iemand naar y = -60"),
            Map.entry("Spawn a hole that goes to the void", "Genereer een gat naar de leegte"),
            Map.entry("Enter creative mode for 10 seconds", "Ga 10 seconden in creatieve modus"),
            Map.entry("Give yourself 4 pieces of TNT", "Geef jezelf 4 stuks TNT"),
            Map.entry("Trap a player in a barrier block cage", "Sluit iemand op in een barrièreblokkooi"),
            Map.entry("Give a player motion sickness: 30 seconds", "Geef een speler reisziekte: 30 seconden"),
            Map.entry("Turn all nearby blocks of a player to stone", "Verander alle blokken bij een speler in steen"),
            Map.entry("Put a curse of binding leather chestplate on someone", "Doe een vloek-van-binding lederen borstplaat op iemand"),
            Map.entry("/clear a RANDOM person's inventory (could be you!!)", "/clear de inventaris van een WILLEKEURIGE speler (kan jij zijn!!)"),
            Map.entry("Make someone leave a bedrock trail: 40 secs", "Laat iemand een bedrockspoor achterlaten: 40 sec"),
            Map.entry("Give someone blindness & darkness: 40 secs", "Geef iemand blindheid en duisternis: 40 sec"),
            Map.entry("Give yourself one ravager spawn egg", "Geef jezelf een ravager spawn-ei"),
            Map.entry("Give yourself an elytra & fireworks", "Geef jezelf elytras en vuurwerk"),
            Map.entry("Give yourself a milk bucket & 2 golden apples", "Geef jezelf een emmer melk en 2 gouden appels"),
            Map.entry("Give yourself a fire resistance potion", "Geef jezelf een vuurbestendigheidsdrankje"),
            Map.entry("Shield yourself from negative items: 3 mins", "Bescherm jezelf tegen negatieve voorwerpen: 3 min"),
            Map.entry("Spawn falling anvils above someone", "Spawn vallende aambeelden boven iemand"),
            Map.entry("Put someone in adventure mode: 40 secs", "Zet iemand in avonturenmodus: 40 sec"),
            Map.entry("Place bells all around someone", "Plaats klokken rondom iemand"),
            Map.entry("Place a layer of lava above someone", "Plaats een laag lava boven iemand"),
            Map.entry("Spawn a horde of bees around someone", "Roep een zwerm bijen rondom iemand op"),
            Map.entry("Give yourself full diamond armor & tools", "Geef jezelf volledig diamanten pantser en gereedschap"),
            Map.entry("Teleport to someone (& surprise attack them?)", "Teleporteer naar iemand (en val hem aan?)"),
            Map.entry("Give yourself 9 obsidian", "Geef jezelf 9 obsidiaan"),
            Map.entry("Strike someone with lightning", "Sla iemand met bliksem"),
            Map.entry("Put a pumpkin head on someone: 1 min", "Doe een pompoenhoofd op iemand: 1 min"),
            Map.entry("Drown someone with a flood of water", "Verdrink iemand met een vloed water"),
            Map.entry("Make someone extremely tiny", "Maak iemand extreem klein"),
            Map.entry("Make someone extremely huge", "Maak iemand extreem groot"),
            Map.entry("Give yourself a totem of undying", "Geef jezelf een totem van onsterfelijkheid"),
            Map.entry("Place a layer of gravel above EVERYONE except you", "Plaats een laag grind boven IEDEREEN behalve jij"),
            Map.entry("Make the swap cycle length 30 seconds shorter", "Maak de wisselcyclus 30 seconden korter"),
            Map.entry("Block out the sun for someone", "Blokkeer de zon voor iemand"),
            Map.entry("Fill up someone's inventory with junk", "Vul iemands inventaris met rommel"),
            Map.entry("Transform the world around someone into the Nether", "Verander de wereld rondom iemand in de Nether"),
            Map.entry("Spawn a bunch of cobwebs on someone", "Spawn een hoop spinnenweb op iemand"),
            Map.entry("Give yourself 3 ender pearls", "Geef jezelf 3 enderpaarlen"),
            Map.entry("Spawn a village right where you are", "Spawn een dorp precies waar je bent"),
            Map.entry("Spawn a desert temple right where you are", "Spawn een desert tempel precies waar je bent"),
            Map.entry("Summon a California earthquake on EVERYONE except you", "Roep een aardbeving op Californisch niveau op voor IEDEREEN behalve jij"),
            Map.entry("Block someone from using any items: 3 mins", "Blokkeer iemand van het gebruiken van voorwerpen: 3 min"),
            Map.entry("Give yourself an enchanted golden apple", "Geef jezelf een betoverd gouden appel"),
            Map.entry("Force a player to look down for 45 secs", "Dwing een speler naar beneden te kijken voor 45 sec"),
            Map.entry("Bombard someone with a ton of ghasts", "Bombardeer iemand met een hoop ghasts"),
            Map.entry("Jumpscare someone", "Laat iemand schrikken"),
            Map.entry("Lock someone into a prison", "Sluit iemand op in een gevangenis"),
            Map.entry("Give yourself a water bucket", "Geef jezelf een emmer water"),
            Map.entry("Give yourself a lava bucket", "Geef jezelf een emmer lava"),
            Map.entry("Give yourself a long fire resistance potion", "Geef jezelf een lang vuurbestendigheidsdrankje"),
            Map.entry("Liquidate all blocks surrounding a player", "Verander alle blokken rondom een speler in water"),
            Map.entry("Set time to midnight (or mid-day if it's night)", "Stel de tijd in op middernacht (of middag als het nacht is)"),
            Map.entry("Spawn a giant slime on someone", "Spawn een reuzensleim op iemand"),
            Map.entry("Give yourself 4 extra hearts for health", "Geef jezelf 4 extra harten voor gezondheid"),
            Map.entry("Take away 2 hearts from someone (leave them w/8)", "Neem 2 harten weg van iemand (laat ze met 8 zitten)"),
            Map.entry("Launch a Viet Cong ambush on someone", "Val iemand aan met een Viet Cong hinderlaag"),
            Map.entry("Give yourself a one-hit-kill sword", "Geef jezelf een één-klap-dood zwaard"),
            Map.entry("Switch game's language to Dutch Nederlands", "Schakel de taal van het spel over naar Engels English!"),
            Map.entry("Set /difficulty to hard", "Stel /difficulty in op moeilijk"),
            Map.entry("Set /difficulty to normal", "Stel /difficulty in op normaal"),
            Map.entry("Set /difficulty to easy", "Stel /difficulty in op gemakkelijk"),
            Map.entry("Teleport someone to a superflat world", "Teleporteer iemand naar een superplatte wereld"),
            Map.entry("Give yourself a crafting table, furnace, & materials", "Geef jezelf een werkbank, oven en materialen"),
            Map.entry("Crash somebody's Minecraft game", "Laat iemands Minecraft-spel crashen"),
            Map.entry("Turn OFF Keep Inventory (or ON if it's off)", "Zet Keep Inventory UIT (of AAN als het uit is)"),
            Map.entry("Put someone into spectator mode: 20 secs", "Zet iemand in toeschouwermodus: 20 sec"),
            Map.entry("Re-shuffle everyone around the world EXCEPT YOU", "Herschud iedereen over de wereld BEHALVE JIJ"),
            Map.entry("Place an Amethyst Geode where you are", "Plaats een Amethist Grot waar je bent"),
            Map.entry("Turn OFF /gamerule natural regeneration (or ON if it's off)", "Zet /gamerule natural regeneration UIT (of AAN als het uit is)"),
            Map.entry("Build a Quartz maze around someone", "Bouw een kwartslabyrint rondom iemand"),
            Map.entry("Turn all blocks near someone to obsidian", "Verander alle blokken bij iemand in obsidiaan"),
            Map.entry("Build a Stalagmite trap next to you", "Bouw een druipsteenval naast je"),
            Map.entry("Delete the Chunk someone's standing in", "Verwijder het chunk waar iemand in staat"),
            Map.entry("Switch places with someone", "Wissel van positie met iemand"),
            Map.entry("Mine blocks faster for 90 seconds", "Mijn blokken sneller voor 90 seconden"),
            Map.entry("Make the game low-gravity: 3 minutes", "Maak het spel lage-zwaartekracht: 3 minuten"),
            Map.entry("Take NO fall damage for the next 5 minutes", "Neem GEEN valschade voor de komende 5 minuten"),
            Map.entry("Make someone's ears bleed (HEADPHONE WARNING!)", "Laat iemands oren bloeden (KOPTELEFOONWAARSCHUWING!)"),
            Map.entry("Summon a Stronghold below you", "Roep een Stronghold onder je op"),
            Map.entry("Give yourself a flint & steel & iron ingot", "Geef jezelf een vuursteen, staal en ijzerstaaf"),
            Map.entry("Put someone into Parkour Civilization (from Youtube)", "Stuur iemand naar Parkour Civilization (van Youtube)"),
            Map.entry("Secretly spy on what someone's currently doing", "Spieer stiekem op wat iemand doet"),
            Map.entry("Shield yourself from negative items: 2.5 mins", "Bescherm jezelf tegen negatieve voorwerpen: 2,5 min"),
            Map.entry("Block someone from using crafting tables: 90 sec", "Blokkeer iemand van het gebruiken van werkbanken: 90 sec"),
            Map.entry("Gain a monster-proof forcefield: 3 mins", "Krijg een monsteri-bestendig krachtschild: 3 min"),
            Map.entry("Spawn a Giant zombie on someone", "Roep een reuzen-zombie op bij iemand"),
            Map.entry("Place a Trial Chamber below you", "Plaats een Proefkamer onder je"),
            Map.entry("Build a Woodland Mansion where you are", "Bouw een Bosmanswoning waar je bent"),
            Map.entry("Make someone continuously pee: 1 min", "Laat iemand continu plassen: 1 min"),
            Map.entry("Get an enchanting table, lapis, & XP", "Verkrijg een toverkist, lapis lazuli en XP"),
            Map.entry("Summon the Warden on someone", "Roep de Warden op bij iemand"),
            Map.entry("Teleport someone directly to the Nether", "Teleporteer iemand direct naar de Nether"),
            Map.entry("Summon Oppenheimer's NUCLEAR bomb on someone", "Roep Oppenheimers KERNBOM op bij iemand"),
            Map.entry("Summon an Ancient City below you", "Roep een Oude Stad onder je op"),
            Map.entry("Set everything around someone on fire", "Steek alles rondom iemand in brand"),
            Map.entry("Spawn 100 Endermen on someone", "Spawn 100 Endermen bij iemand"),
            Map.entry("Spawn 3 chicken jockeys on someone", "Spawn 3 kippenjockeys op iemand"));
}
